---
# The main magento playbook
# Mischa van den Burg & Gino Kok

- name: Containerize Magento
  hosts: all
  become: true

  vars_prompt:
  - name: "create_partition"
    prompt: "Do you want to create a partition (yes/no)?"
    private: no

  roles:
    - role: docker_installer
    - role: make_partition
      when: create_partition | bool
