---
# The main magento playbook
# Mischa van den Burg & Gino Kok

- name: Containerize Magento
  hosts: all
  become: true

  vars_prompt:
  # prompt the user if the creation of a partition is required
  - name: "create_partition"
    prompt: "Do you want to create a partition (yes/no)?"
    private: no

  # Retrieve the directory that holds the apps, appl & data folder
  - name: "root_directory"
    prompt: "Please provide the directory where Magento's application & data will be stored"
    private: no

  # Retrieve what version of the deploy needs to be used (defaults to "main")
  - name: "deploy_version"
    prompt: "What version do you want to use? (leave blank for latest)"
    private: no
    default: "main"

  roles:
    - role: docker_installer
    - role: make_partition
      when: create_partition | bool
    - role: containerize_magento
      vars:
        clone_location: "/tmp/magento"
        repository: "https://github.com/ginokok1996/Technative-DevOps-Scripts.git"
        deploy_version: "{{ deploy_version }}"
        root_directory: "{{ root_directory }}"
        dirNames: ['appl', 'apps', 'data', 'config']
